# Generated by Django 6.0.1 on 2026-02-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='dau_metric',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='grades_qa',
            field=models.TextField(blank=True, default=''),
        ),
    ]
