# Generated by Django 6.0.1 on 2026-02-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_dailyreport_dau_metric_dailyreport_grades_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('WFH', 'Work From Home'), ('Leave', 'Leave'), ('Half Day', 'Half Day')], max_length=20),
        ),
    ]
