# Generated by Django 6.0.1 on 2026-02-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_attendance_check_in_time_attendance_check_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='extra_days',
            field=models.BooleanField(default=False, help_text='Check if worked on Sunday or weekend'),
        ),
    ]
