# Generated by Django 6.0.2 on 2026-02-26 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_generatedcredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='today_actions',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='additional_actions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='team_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, choices=[('Growth and Marketing', 'Growth and Marketing'), ('Tech and Development', 'Tech and Development')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
